#!/usr/bin/env sh

background_file=$HOME/.config/current_background

# step 1: get current background
current_background=$(cat $background_file)
if [ "$current_background" = "light" ]; then
	current_background="dark"
else
	current_background="light"
fi

# step 2: write current background so every process can access it
echo $current_background > $background_file

# step 3: change .Xresources
# TODO: having an #include in .Xresources to the colorscheme of st, then we can do:
# 1. update the st-colors file:
#   $ ln -sf new-background xresources-colors
# 2. reload the x resources database:
#   $ xrdb ~/.Xresources

# step 4: reload every neovim instance
pidof nvim | xargs kill -s USR1

# step 5: reload every st instance
pidof st | xargs kill -s USR1

# step 6: update tmux variable and reload tmux configuration
tmux set-environment -g BACKGROUND $current_background; tmux source-file $HOME/.tmux.conf

cat $background_file
