#!/usr/bin/env zsh

DEFAULT_TIMEZONE="America/Argentina/Buenos_Aires"

if [ -z "$TZ" ]; then
  export TZ="$DEFAULT_TIMEZONE"
fi

color=""
if [[ "$TZ" == "$DEFAULT_TIMEZONE" ]]; then
  color="-C 6"
fi

name=$(echo $TZ | sed 's/.*\/\(.*$\)/\1/' | tr '_' ' ')
(st -f "monospace:size=16" -t clock zsh -c 'tty-clock -B -n -c '$color' -f "'$name' :: %d/%m/%Y"') &
