#!/bin/bash

source ~/.colors

find_git_branch() {
  # Based on: http://stackoverflow.com/a/13003854/170413
  local branch
  if branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null); then
    if [[ "$branch" == "HEAD" ]]; then
      branch='detached*'
    fi
    echo "[$branch]"
  fi
}

find_git_dirty() {
  local status=$(git status --porcelain 2> /dev/null)
  if [[ "$status" != "" ]]; then
    echo "* "
  fi
}

find_git_dir() {
  local git_status=$(git rev-parse --git-dir 2> /dev/null)
  if [ "$git_status" ]; then
    local branch=$(find_git_branch)
    local dirty=$(find_git_dirty)
    git_prompt="$txtcyn$branch$txtrst $txtred$dirty$txtrst"
  else
    git_prompt=""
  fi
}

PROMPT_COMMAND="find_git_dir; $PROMPT_COMMAND"
