#!/usr/bin/env zsh

set -e

# mdview creates a pdf file from a Markdown file and opens it to view
# it, this depends on 3 other binaries:
#  - pandoc
#  - wkhtmltopdf
#  - zathura

binname=${0:t:r}
usage() {
  echo "$binname: $1"
  echo ""
  echo "usage: mdview [markdown file]"
  exit 1
}

if [ -z "$1" ]; then
  usage "missing input file"
fi
input=$1
shift

fname=${input:t:r}
htmlout=/tmp/$fname.html
pdfout=/tmp/$fname.pdf

# transform the input .md file into an .html
pandoc --template=github --self-contained $input -o $htmlout

# transform the intermediate .html into a .pdf and remove the .html
wkhtmltopdf $htmlout $pdfout
rm $htmlout

show_pdf() {
  zathura $pdfout
  rm $pdfout
}

# show pdf in the background so we can continue with our work
show_pdf &
