#!/bin/sh

# This file is invoked from sxiv by pressing C-x and
# then another mapping

while read -r file; do
  case "$1" in
  "C-d")
    trash-put "$file"
    ;;
  "C-c")
    printf "%s" "$file" | xclip -selection clipboard
    ;;
  esac
done
