#!/bin/sh

# This file is invoked from sxiv by pressing C-x and
# then another mapping

while read file
do
        case "$1" in
        "C-d")
                trash-put "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        esac
done
