log-level = "warn";

# xrender, glx, or xr_glx_hybrid
backend = "xrender";

# redraw the WHOLE screen every time: bad performance, but no artifacts
use-damage = false;

# do not draw any shadow on windows
shadow = false;
