#!/bin/sh
# switch power state using dmenu(1)

selection=$(printf 'lock\npoweroff\nreboot' | dmenu -p \? -f -i -nb '#222' -nf '#bbb' -sb '#c20' -bo '#c20' -sf '#eee' -fn monospace:size=24)

case "${selection}" in
	lock)
		slock
		;;
	reboot)
		sudo reboot
		;;
	poweroff)
		sudo shutdown -h now
		;;
esac
