#!/bin/sh

# set monitor output
hdmi_mode="$(xrandr -q | grep -A1 "HDMI-1 connected" | tail -1 | awk '{ print $1 }')"
vga_mode="$(xrandr -q | grep -A1 "VGA-0 connected" | tail -1 | awk '{ print $1 }')"
edp_mode="$(xrandr -q | grep -A1 "eDP-1 connected" | tail -1 | awk '{ print $1 }')"
if [ -n "$hdmi_mode" ]; then
  # extra hdmi monitor layout
  xrandr --output HDMI-1 --mode "$hdmi_mode" --pos 0x0 --rotate normal --output eDP-1 --primary --mode "$edp_mode" --pos 282x1080 --rotate normal
else
  if [ -n "$vga_mode" ]; then
    # virtual layout
    xrandr --output VGA0 --mode "$vga_mode" --pos 0x0 --rotate normal
  else
    # no extra monitor layout
    xrandr --output eDP-1 --mode "$edp_mode" --pos 0x0 --rotate normal
  fi
fi

# set background
feh --bg-fill '/usr/share/images/wall.jpg'

# set keyboard layout
#
# NOTE: all options can be found at /usr/share/X11/xkb/rules/base.lst
#
# -layout us                      set the keyboard layout to US
# -variant altgr-intl             set the variant to use AltGr for áéíóú ÁÉÍÓÚ ñÑ
# -option                         clear all options
# -option ctrl:nocaps             capslock behave like ctrl
# -option altwin:swap_alt_win     swaps alt and win keys
# -option lv3:ralt_switch         remaps Alt_R to AltGr
setxkbmap \
  -layout us \
  -variant altgr-intl \
  -option \
  -option ctrl:nocaps \
  -option altwin:swap_alt_win \
  -option lv3:ralt_switch

# run conky in background
(conky -q|while read LINE;do xsetroot -name "$LINE";done) &

# start a terminal (with tmux)
(sleep 1s; st -e tmux) &

# start browsers
(sleep 2s; chromium) &
(sleep 3s; opera) &

# start chats
(sleep 4s; slack) &
(sleep 5s; mattermost-desktop) &

# systray icons
(sleep 10s; nm-applet) &
(sleep 12s; blueman-applet) &
(sleep 14s; volumeicon) &

# start dropbox
if [ -f ~/bin/dropbox.py ]; then
  (sleep 60s; ~/bin/dropbox.py start) &
fi

# set xautolock to lock screen after 5 minutes
# (sleep 240s; xautolock -time 5 -locker slock) &

# start dwm
exec dwm
