#!/usr/bin/env zsh

# set monitor output
hdmi_mode="$(xrandr -q | grep -A1 "HDMI-1 connected" | tail -1 | awk '{ print $1 }')"
vga_mode="$(xrandr -q | grep -A1 "VGA-0 connected" | tail -1 | awk '{ print $1 }')"
edp_mode="$(xrandr -q | grep -A1 "eDP-1 connected" | tail -1 | awk '{ print $1 }')"
if [ -n "$hdmi_mode" ]; then
  # extra hdmi monitor layout
  xrandr --output HDMI-1 --mode "$hdmi_mode" --pos 0x0 --rotate normal --output eDP-1 --primary --mode "$edp_mode" --pos 282x1080 --rotate normal
else
  if [ -n "$vga_mode" ]; then
    # virtual layout
    xrandr --output VGA0 --mode "$vga_mode" --pos 0x0 --rotate normal
  else
    # no extra monitor layout
    xrandr --output eDP-1 --mode "$edp_mode" --pos 0x0 --rotate normal
  fi
fi

# desktop wallpaper
feh --bg-scale ~/dotfiles/saturn_from_casini.png

# start the session with some programs open
(st -e tmux) &
(sleep 1s; google-chrome) &
(sleep 2s; slack) &
(sleep 3s; firefox) &

# systray && systray icons
(slstatus) &
(sleep 1s; wpa_gui -t -i wlp0s20f3) &

# day of week, if we are in a weekday then execute work script
dow=$(date +"%u")
if [[ $dow -ge 1 && $dow -le 5 ]]; then
  work
fi

# start dwm
exec dwm
