#!/usr/bin/env zsh

# set monitor output
hdmi_mode="$(xrandr -q | grep -A1 "HDMI-1 connected" | tail -1 | awk '{ print $1 }')"
vga_mode="$(xrandr -q | grep -A1 "VGA-0 connected" | tail -1 | awk '{ print $1 }')"
edp_mode="$(xrandr -q | grep -A1 "eDP-1 connected" | tail -1 | awk '{ print $1 }')"
virt_mode="$(xrandr -q | grep -A1 "Virtual-1 connected" | tail -1 | awk '{ print $1 }')"
if [ -n "$hdmi_mode" ]; then
  # extra hdmi monitor layout
  xrandr --output HDMI-1 --mode "$hdmi_mode" --pos 0x0 --rotate normal --output eDP-1 --primary --mode "$edp_mode" --pos 282x1080 --rotate normal
else
  if [ -n "$vga_mode" ]; then
    # old virtual layout
    xrandr --output VGA0 --mode "$vga_mode" --pos 0x0 --rotate normal
  else
    if [ -n "$virt_mode" ]; then
      # virtual layout
      xrandr --output Virtual-1 --mode 1920x1080 --pos 0x0 --rotate normal
    else
      # no extra monitor layout (in a laptop)
      xrandr --output eDP-1 --mode "$edp_mode" --pos 0x0 --rotate normal
    fi
  fi
fi

# set keyboard layout
#
# NOTE: all options can be found at /usr/share/X11/xkb/rules/base.lst
#
# -layout us                      set the keyboard layout to US
# -variant altgr-intl             set the variant to use AltGr for áéíóú ÁÉÍÓÚ ñÑ
# -option                         clear all options
# -option ctrl:nocaps             capslock behave like ctrl
# -option altwin:swap_alt_win     swaps alt and win keys
# -option lv3:ralt_switch         remaps Alt_R to AltGr
setxkbmap \
  -layout us \
  -variant altgr-intl \
  -option \
  -option ctrl:nocaps \
  -option altwin:swap_alt_win \
  -option lv3:ralt_switch

# desktop wallpaper
feh --bg-scale ~/dotfiles/saturn_from_casini.png

# # start the session with some programs open
(st -e tmux) &
(sleep 1s; google-chrome) &
(sleep 2s; slack) &
(sleep 3s; firefox) &
(sleep 4s; new-godo-window) &

# systray && systray icons
(slstatus) &
(sleep 1s; wpa_gui -t -i wlp0s20f3) &

# # clocks to show different timezones
TZ='Europe/Madrid' clock
TZ='America/Argentina/Buenos_Aires' clock
TZ='US/Mountain' clock
TZ='Asia/Bangkok' clock

# set grid layout on tag 9 of dwm after 30 seconds
(sleep 1s; xdotool key super+9 key super+g key super+1) &

# start dwm
exec dwm
